# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [4]:
range_value=np.arange(10,49)
print(range_value)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [5]:
shape = np.shape(range_value)
print(shape)

(39,)


5. Print the type of the previous array in question 3

In [6]:
range_value.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [7]:
print(f"Numpy Version is {np.__version__}")
print("-----------------------\n")
print("Numpy Configuration is \n")
print(np.show_config())

Numpy Version is 1.18.1
-----------------------

Numpy Configuration is 

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/dell/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/dell/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/dell/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/dell/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/dell/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/dell/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/dell/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/dell/anaconda3/include']
None


7. Print the dimension of the array in question 3


In [8]:
range_value.ndim

1

8. Create a boolean array with all the True values

In [36]:
bool_arr = np.ones(10, dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
two_arr= np.array([[1,2,3],[4,5,6]])
print(two_arr)
print("-------------")
atwo_arr= np.arange(9).reshape(3,3)
print(atwo_arr)

[[1 2 3]
 [4 5 6]]
-------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Create a three dimensional array



In [10]:
three_arr= np.arange(27).reshape(3,3,3)
three_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
rev_vec= np.arange(10)
print(f"Actual{rev_vec}")
print(f"Reverse {rev_vec[::-1]}")

Actual[0 1 2 3 4 5 6 7 8 9]
Reverse [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null_vector=np.zeros(10)
print(null_vector)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
iden_mat=np.identity(3)
print(iden_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr=np.array([1,2,3,4,5])
arr.astype(np.float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1.shape
arr2.shape
np.dot(arr1,arr2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

17. Extract all odd numbers from arr with values(0-9)

18. Replace all odd numbers to -1 from previous array

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [50]:
arr = np.arange(10)
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
two_border=np.ones((10,10))
two_border[1:9,1:9]=0
print(two_border)

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
arr_two = np.arange(10).reshape(2,5)
print(arr_two)
arr_two[0,:]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
arr_two = np.arange(10).reshape(2,5)
print(arr_two)
arr_two[1:2,1:2]

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
arr_two = np.arange(10).reshape(2,5)
print(arr_two)
arr_two[0:2,2:5]

26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
ran_val= np.random.random((10,10))
ran_val_min, ran_val_max= ran_val.min(), ran_val.max()
print(ran_val_min, ran_val_max)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Commom Values are {np.intersect1d(a, b)}")

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
two_dim= np.arange(15.0).reshape(5,3)
two_dim

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [79]:
newarray = np.arange(1, 17).reshape(2,2,4)
newarray

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [22]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
diff=np.setdiff1d(a,b)
print(diff)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [66]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum